export const bgColor = "bg-white ";
export const modalContainer:string =  "z-40 p-10 cursor-default outline outline-blue-500 outline-4 " + bgColor;
export const modalIcons:string =  'md:ml-4 lg:ml-7 text-[20px] md:text-[35px] text-red-500 ';
export const modalHeaderContainer:string =  "text-sm md:text-3xl px-5 py-2 md:flex flex justify-center ";
export const modalContentContainer: string = 'mb-3 text-sm md:text-lg lg:text-2xl flex flex-col gap-1 justify-center ';
export const button: string = "bg-gray-500 text-white px-3 py-1 cursor-pointer rounded-lg w-fit focus:outline-none focus:ring focus:ring-white ";
export const disabledButton: string = `${button} cursor-default bg-gray-400`
export const closeButton: string = `${button} hover:bg-red-500 active:bg-red-600 `;
export const submitButton: string = `${button} hover:bg-blue-500 active:bg-blue-600 `;
export const pageDivider: string = "border-black w-100 my-3 ";
